### ISSUE TITLE
自定义主题没效果

### ISSUE THREAD

**Issue by daimayaojing** [alibaba-bizcharts/bx-docs#10]
自己定义的fontFamily没显示效果

const FONT_FAMILY = '"DINalternate-bold", "BlinkMacSystemFont", "Roboto", "Helvetica Neue", Helvetica, Arial, "PingFang SC","-apple-system", "Hiragino Sans GB", "Source Han Sans CN", Noto Sans CJK SC, Microsoft YaHei, Microsoft Jhenghei, SimHei, STXihei, YouYuan, sans-serif !important';
const Theme = {
    animate:false,
    fontFamily: FONT_FAMILY,
    colors:{},
	shapes:{},
}
BizCharts.setTheme(Theme);

**Comment by Leannechn** [comment]
自定义主题文档已更新。请参考最新的配置文档 https://bizcharts.net/products/bizCharts/api/theme
